
services:
  app:
    image: node:18-alpine
    build:
      dockerfile: ./Dockerfile
      context: .
    command: sh -c "npx prisma migrate dev --name init && npm run start:dev"
    ports:
      - ${PORT}:${PORT}
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - PORT=${PORT}
    depends_on:
      - postgres
  
  postgres:
    image: postgres
    volumes:
      - postgres_vol:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

volumes:
  postgres_vol:

