version: '3'

services:
  database:
    image: postgres
    container_name: yvolha/database
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - docker-network
    build:
      dockerfile: ./prisma/Dockerfile
      context: .
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    container_name: yvolha/app
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    restart: always
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - database
    networks:
      - docker-network

  