
services:
  app:
    image: node:18-alpine
    command: sh -c "npm install && npm run start:dev"
    ports:
      - ${PORT}:${PORT}
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      PORT: ${PORT}
  
  postgres:
    image: postgres
    volumes:
      - postgres_vol:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - 5432:5432

volumes:
  postgres_vol:

