version: '3'

services:
  database:
    image: postgres
    container_name: database
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    build:
      dockerfile: ./prisma/Dockerfile
      context: .
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    container_name: app
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - .:/app
    restart: always
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - database


  